<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rakit" failures="1" tests="4" name="Products Test" time="24.024" errors="0" timestamp="2023-09-23T20:59:54 IST">
  <testcase classname="testcases.VerifyProduct" name="VerifyProducts" time="3.856"/>
  <testcase classname="testcases.VerifyProduct" name="searchProduct" time="5.455"/>
  <testcase classname="testcases.VerifyProduct" name="addFirstAndSecondProductsToCart" time="7.134"/>
  <testcase classname="testcases.VerifyProduct" name="verifyProdQuantity" time="5.52">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
at resuableFunctions.ResuableClass.innerTextEquals(ResuableClass.java:53)
at testcases.VerifyProduct.verifyProdQuantity(VerifyProduct.java:92)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyProdQuantity -->
</testsuite> <!-- Products Test -->
